-- MySQL Script generated by MySQL Workbench
-- Mon Oct 13 22:49:05 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dataskilldb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dataskilldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dataskilldb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dataskilldb` ;

-- -----------------------------------------------------
-- Table `dataskilldb`.`auto_avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataskilldb`.`auto_avaliacao` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `data_auto_avaliacao` DATETIME(6) NULL DEFAULT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dataskilldb`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataskilldb`.`departamento` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dataskilldb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataskilldb`.`usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cargo` ENUM('COLABORADOR', 'DIRETOR', 'SUPERVISOR') NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `senha` VARCHAR(255) NULL DEFAULT NULL,
  `auto_avaliacao_id` BIGINT NULL DEFAULT NULL,
  `departamento_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK5171l57faosmj8myawaucatdw` (`email` ASC) VISIBLE,
  UNIQUE INDEX `UKg8jciwayohmnyoy9f5nbvksi4` (`auto_avaliacao_id` ASC) VISIBLE,
  INDEX `FKocc0ask6a7y4t7aw60t7ujfhb` (`departamento_id` ASC) VISIBLE,
  CONSTRAINT `FK1wmnrshc7m13wce4fjghy8mi6`
    FOREIGN KEY (`auto_avaliacao_id`)
    REFERENCES `dataskilldb`.`auto_avaliacao` (`id`),
  CONSTRAINT `FKocc0ask6a7y4t7aw60t7ujfhb`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `dataskilldb`.`departamento` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dataskilldb`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataskilldb`.`avaliacao` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `data_avaliacao` DATETIME(6) NULL DEFAULT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKik01lj37b4mcswtkppjc9yket` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `FKik01lj37b4mcswtkppjc9yket`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dataskilldb`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dataskilldb`.`certificadp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataskilldb`.`certificadp` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `data_fim` DATETIME(6) NOT NULL,
  `data_inicio` DATETIME(6) NOT NULL,
  `instituicao` VARCHAR(255) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKoymicpmvksyunsdvefmfmo0ja` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `FKoymicpmvksyunsdvefmfmo0ja`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dataskilldb`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dataskilldb`.`experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataskilldb`.`experiencia` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(255) NULL DEFAULT NULL,
  `data_fim` DATE NULL DEFAULT NULL,
  `data_inicio` DATE NULL DEFAULT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `nome_empresa` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK3h6736sjl6yjxum4lohstrkyi` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `FK3h6736sjl6yjxum4lohstrkyi`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dataskilldb`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dataskilldb`.`hard_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataskilldb`.`hard_skill` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` ENUM('ANGULAR', 'CSHARP', 'CSS', 'HTML', 'JAVA', 'JAVASCRIPT', 'MYSQL', 'PYTHON', 'SPRING') NULL DEFAULT NULL,
  `id_usuario` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKkn36b9a8qgnsic2e7slxm9eqq` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `FKkn36b9a8qgnsic2e7slxm9eqq`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dataskilldb`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dataskilldb`.`soft_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataskilldb`.`soft_skill` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` TINYINT NULL DEFAULT NULL,
  `id_usuario` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKt5ucu4slnakje7d22mar807ee` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `FKt5ucu4slnakje7d22mar807ee`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dataskilldb`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
