spring:
  application:
    name: dataskill
  datasource:
    url: jdbc:mysql://localhost:3306/dataskilldb
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
      enabled:true
      baseline-on-migrate:true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true